image: git.academy.b9lab.com:5050/ida-p4-exercise-week-2/exercise-code:386e322

stages:
  - test

test:
  tags:
    - shared-runner-1
  script:
    - bash -c /original/score-ci.sh
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
